- hosts: all
  become: yes
  tasks:
    - name: create user 
      user: name="{{ user }}" append=yes state=present createhome=yes shell=/bin/bash
 
    - name: allow user kubeuser to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '"{{ user }}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
 
    - name: set up authorized keys for the ubuntu user
      authorized_key: user="{{ user }}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Print the created user.
      shell: id "{{ user }}"
      register: new_user_created

    - debug:
        msg: "{{ new_user_created.stdout_lines[0] }}"